/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <string>
#include<opencv2/opencv.hpp>
#include<iostream>
#include <opencv2/imgproc/types_c.h>
#include <unistd.h>

using namespace cv;
using namespace std;

/* Header for class com_mp5a5_opencv_NativeLibUtils */

#ifndef _Included_com_mp5a5_opencv_NativeLibUtils
#define _Included_com_mp5a5_opencv_NativeLibUtils
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jintArray JNICALL
Java_com_mp5a5_opencv_NativeLibUtils_bitmap2Gray(JNIEnv *, jobject, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
